# Generated by Django 3.0.2 on 2020-01-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200114_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.ImageField(choices=[(0, 'Nieznany'), (2, 'Komedia'), (3, 'Sci-Fi'), (1, 'Horror'), (4, 'Drama')], default=0, upload_to=''),
        ),
    ]
