# Generated by Django 3.0.2 on 2020-01-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200114_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.ImageField(choices=[(0, 'Nieznany'), (4, 'Drama'), (1, 'Horror'), (3, 'Sci-Fi'), (2, 'Komedia')], default=0, upload_to=''),
        ),
    ]
