# Generated by Django 3.0.2 on 2020-01-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200114_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.ImageField(choices=[(2, 'Komedia'), (4, 'Drama'), (0, 'Nieznany'), (1, 'Horror'), (3, 'Sci-Fi')], default=0, upload_to=''),
        ),
    ]
