# Generated by Django 3.0.2 on 2020-01-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200114_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='info',
        ),
        migrations.AddField(
            model_name='movie',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExtraInfo',
        ),
    ]
