# Generated by Django 3.0.2 on 2020-01-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200114_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(4, 'Drama'), (1, 'Horror'), (2, 'Komedia'), (0, 'Nieznany'), (3, 'Sci-Fi')], default=0),
        ),
    ]
