# Generated by Django 3.0.2 on 2020-01-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200114_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(2, 'Komedia'), (0, 'Nieznany'), (4, 'Drama'), (3, 'Sci-Fi'), (1, 'Horror')], default=0),
        ),
    ]
