# Generated by Django 3.0.2 on 2020-01-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=128)),
                ('nazwisko', models.CharField(max_length=120)),
                ('filmy', models.ManyToManyField(to='main.Movie')),
            ],
        ),
    ]
